node {
  stage('checkout') {
    git 'https://github.com/superpeace/spring-mvc-showcase.git'
  }
  stage('maven install') {
    sh 'mvn clean install'
  }
  stage('Unit Test') {
    sh 'mvn test'
  }

}