node {
  stage('build') {
    openshiftBuild(buildConfig: 'exntu-prd-showcase', showBuildLogs: 'true')
  }
  stage('deploy') {
    openshiftDeploy(deploymentConfig: 'exntu-prd-showcase')
  }

}
